
-- -- Utilities for creating configurations
-- require("formatter").setup({
-- 	-- Enable or disable logging
-- 	logging = true,
-- 	-- Set the log level
-- 	log_level = vim.log.levels.WARN,
-- 	-- All formatter configurations are opt-in
-- 	filetype = {
-- 		lua = {
-- 			require("formatter.filetypes.lua").stylua,
-- 		},
-- 		go = {
-- 			require("formatter.filetypes.go").gofumpt,
-- 		},
-- 		ts = {
-- 			require("formatter.filetypes.go").prettier,
-- 		},
-- 	},
-- })
--
-- local augroup = vim.api.nvim_create_augroup
-- local autocmd = vim.api.nvim_create_autocmd
--
-- augroup("__formatter__", { clear = true })
-- autocmd("BufWritePost", {
-- 	group = "__formatter__",
-- 	command = ":FormatWrite | :retab",
-- })
